// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by AvroGenerated, version 1.0.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroGenerated
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum SampleEnum
	{
		S1,
		S2,
		S3,
	}
}
