// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by AvroGenerated, version 1.0.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroGenerated
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SampleNestedClass : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SampleNestedClass\",\"namespace\":\"AvroGenerated\",\"fields\":" +
				"[{\"name\":\"a\",\"type\":\"long\"},{\"name\":\"b\",\"type\":\"string\"}]}");
		private long _a;
		private string _b;
		public virtual Schema Schema
		{
			get
			{
				return SampleNestedClass._SCHEMA;
			}
		}
		public long a
		{
			get
			{
				return this._a;
			}
			set
			{
				this._a = value;
			}
		}
		public string b
		{
			get
			{
				return this._b;
			}
			set
			{
				this._b = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.a;
			case 1: return this.b;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.a = (System.Int64)fieldValue; break;
			case 1: this.b = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
