// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by AvroGenerated, version 1.0.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroGenerated
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SampleClass : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SampleClass"",""namespace"":""AvroGenerated"",""fields"":[{""name"":""value1"",""type"":""long""},{""name"":""value2"",""type"":[""null"",""string""]},{""name"":""value3"",""type"":{""type"":""enum"",""name"":""SampleEnum"",""namespace"":""AvroGenerated"",""symbols"":[""S1"",""S2"",""S3""]}},{""name"":""value4"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""value5"",""type"":{""type"":""record"",""name"":""SampleNestedClass"",""namespace"":""AvroGenerated"",""fields"":[{""name"":""a"",""type"":""long""},{""name"":""b"",""type"":""string""}]}}]}");
		private long _value1;
		private string _value2;
		private AvroGenerated.SampleEnum _value3;
		private IList<System.String> _value4;
		private AvroGenerated.SampleNestedClass _value5;
		public virtual Schema Schema
		{
			get
			{
				return SampleClass._SCHEMA;
			}
		}
		public long value1
		{
			get
			{
				return this._value1;
			}
			set
			{
				this._value1 = value;
			}
		}
		public string value2
		{
			get
			{
				return this._value2;
			}
			set
			{
				this._value2 = value;
			}
		}
		public AvroGenerated.SampleEnum value3
		{
			get
			{
				return this._value3;
			}
			set
			{
				this._value3 = value;
			}
		}
		public IList<System.String> value4
		{
			get
			{
				return this._value4;
			}
			set
			{
				this._value4 = value;
			}
		}
		public AvroGenerated.SampleNestedClass value5
		{
			get
			{
				return this._value5;
			}
			set
			{
				this._value5 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.value1;
			case 1: return this.value2;
			case 2: return this.value3;
			case 3: return this.value4;
			case 4: return this.value5;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.value1 = (System.Int64)fieldValue; break;
			case 1: this.value2 = (System.String)fieldValue; break;
			case 2: this.value3 = (AvroGenerated.SampleEnum)fieldValue; break;
			case 3: this.value4 = (IList<System.String>)fieldValue; break;
			case 4: this.value5 = (AvroGenerated.SampleNestedClass)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
