module Pulsar.Client.Common.RetryMessageUtil

[<Literal>]
let SYSTEM_PROPERTY_RECONSUMETIMES = "RECONSUMETIMES"
[<Literal>]
let SYSTEM_PROPERTY_DELIVER_AT = "DELIVER_AT"
[<Literal>]
let SYSTEM_PROPERTY_REAL_TOPIC = "REAL_TOPIC"
[<Literal>]
let SYSTEM_PROPERTY_RETRY_TOPIC = "RETRY_TOPIC"
[<Literal>]
let SYSTEM_PROPERTY_ORIGIN_MESSAGE_ID = "ORIGIN_MESSAGE_IDY_TIME"

[<Literal>]    
let MAX_RECONSUMETIMES = 16
[<Literal>]
let RETRY_GROUP_TOPIC_SUFFIX = "-RETRY"
[<Literal>]
let DLQ_GROUP_TOPIC_SUFFIX = "-DLQ"

