// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sample.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SearchRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"query")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Query { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"page_number")]
    public int PageNumber { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"result_per_page")]
    public int ResultPerPage { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public Corpus corpus { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum Corpus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNIVERSAL")]
        Universal = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WEB")]
        Web = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IMAGES")]
        Images = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LOCAL")]
        Local = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"NEWS")]
        News = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCTS")]
        Products = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"VIDEO")]
        Video = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
