<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>3186</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Expect.fs" />
    <Compile Include="ManualInvokeScheduler.fs" />
    <Compile Include="Common\Properties.fs" />
    <Compile Include="Common\HashTests.fs" />
    <Compile Include="Common\TopicNameTests.fs" />
    <Compile Include="Common\CommandTests.fs" />
    <Compile Include="Common\NamespaceNameTests.fs" />
    <Compile Include="Common\ExceptionsTests.fs" />
    <Compile Include="Common\ToolsTests.fs" />
    <Compile Include="Common\MessageTests.fs" />
    <Compile Include="Api\ServiceUriTests.fs" />
    <Compile Include="Api\ConfigurationTests.fs" />
    <Compile Include="Api\ConsumerBuilderTests.fs" />
    <Compile Include="Api\ProducerBuilderTests.fs" />
    <Compile Include="Api\PulsarClientBuilderTests.fs" />
    <Compile Include="Api\AutoClusterFailoverTests.fs" />
    <Compile Include="Internal\EndPointResolverTests.fs" />
    <Compile Include="Internal\BatchMessageContainerTests.fs" />
    <Compile Include="Internal\CompressionCodecTests.fs" />
    <Compile Include="Internal\AcknowledgmentsGroupingTrackerTests.fs" />
    <Compile Include="Internal\UnAckedMessageTrackerTests.fs" />
    <Compile Include="Internal\NegativeAcksTracker.fs" />
    <Compile Include="Internal\SchemaTests.fs" />
    <Compile Include="Internal\TaskSeq.fs" />
    <Compile Include="Internal\StatsTests.fs" />
    <Compile Include="Internal\ChunkedMessageTrackerTests.fs" />
    <Compile Include="Internal\Transaction.fs" />
    <Compile Include="Tests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pulsar.Client.Proto\Pulsar.Client.Proto.csproj" />
    <ProjectReference Include="..\..\src\Pulsar.Client\Pulsar.Client.fsproj" />
    <ProjectReference Include="..\AvroGenerated\AvroGenerated.csproj" />
    <ProjectReference Include="..\ProtobufNativeGenerated\ProtobufNativeGenerated.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Expecto" Version="10.2.3" />
    <PackageReference Include="Expecto.FsCheck" Version="10.2.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.15.5" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>
